### ISSUE TITLE
Assembly Day Pt.3 - Assembly and Documentation of the SolarBox Process

### ISSUE THREAD

**Issue by mikelovic** [CollectiveOpenSourceHardware/LibreSolarBox#33]
# Assembly Workshop at the Fablab St.Pauli, 08. July 2018

### Preparation Steps
- Software tools
  - FreeCAD, 
- Prepare of tools and place
  - table
  - crimping tool
  - screwdriver
  - side cutter
  - allen wrench
- Prepare material and components
  - Frame and Housing (in this case UniProKit)
    - screws, nuts
    - T-slot alu profile
    - 3D printed corner elements / connectors
    - bottom plate
    - housing plates
  - Battery pack
    - 3D printed battery case (bottom and cap -> download link to file)
    - batteries
    - battery connectors
  - electrical components
    - Libre Solar components -> MPPT, BMS, (optional: CAN2Wifi)
    - (optional: RaspberryPi0)
    - wires - power wires (6 sq mm), balancing wires (2 sq mm)
    - ferrules, cable lugs
    - (optional: communication wire - ethernet cable)
   - plugs
     - dc-output plugs (car plug, 2x)
     - solar input plugs (Weidmüller PV Stick allows assembly w/o crimping and is compatible to MC4. Clips should be removed that the plug can be unmounted without tools)
     - usb plugs
     - ON/OFF switch, pushbutton, integrated LED
     - (optional: RJ45 jacks (2x))
     - (optional: epaper display+conncetion wire)

### Assembly Steps
1. Frame assembly
 1.1 nuts into t-slot profile (
 1.2 place profile in rectangle, place corner elements between profiles, screw together
 1.3 repeat 
-> result: 2 connected rectangle frame
 1.4 connect the 2 rectangle frames with profile
-> result: boxframe
2. screw bottom plate on bottom side of boxframe
-> boxframe with bottom plate
3. cut and crimping wires
 3.1 ...
4. battery pack assembly -> !!!!!safety note!!!!!
 4.1 put battery cells in battery case (bottom part)
 4.2 connect battery cells together
 4.3 connect balancing wires with cells
 4.4 connect power wires with battery cells
 4.5 screw battery pack with bottom plate
5. mouting of electric components
...

**Comment by case06** [comment]
Making fotos for instructional of each phase when dissassembling:

If possible, it would be great if you could make also some fotos, which shows for each side the placement (and numbers) of the nuts (sitting in the slots).  This is the key-information needed when assembling a box the first time, in order to avoid repeatedly re-opening the frame for adding some forgotten nuts  .  Having that key would be a real  nice improvement of our doku 😃

Aehm ... macht einfach möglichst viele fotos beim  disasssemblen, ich such mri dann schon das passende raus.  Und welch besonders wichtig sind, das hatte ich schon gepostet:   Fotos, welche zeigen, wo und wieviel Nutenplatten im T-Slot stecken, wenn die Seitenplatten entfernt sind.  Und die von jeder Seite einzeln. Damit man die von vornherein korrekt abzählen kann und nicht immer wieder die Verbindungen neu aufmachen muss, weil man diese oder jene Nutenplatte vergessen hat.
